services:
  douyin:
    build:
      context: .
    ports:
      - "8000:8000"
    container_name: douyin-crawler
    restart: unless-stopped
    environment:
      DOUYIN_HOST: 0.0.0.0
      DOUYIN_PORT: 8000
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./download:/app/download
